import { motion } from 'framer-motion';
import { Brain, TrendingUp } from 'lucide-react';

interface FlowBreakdown {
  category: string;
  value: number;
  color: string;
  pct: number;
}

export default function AIAnalysisPanel() {
  const breakdown: FlowBreakdown[] = [
    { category: 'BTC', value: 184, color: '#F0B90B', pct: 35 },
    { category: 'ETH', value: 92, color: '#3B82F6', pct: 20 },
    { category: 'Altcoins', value: 69, color: '#8B5CF6', pct: 15 },
    { category: 'Forex', value: 92, color: '#10B981', pct: 18 },
    { category: 'Commodities', value: 61, color: '#F59E0B', pct: 12 },
  ];

  const topMovers = [
    { name: 'BTC/USDT', count: 42, netFlow: 156, isPositive: true },
    { name: 'ETH/USDT', count: 38, netFlow: 89, isPositive: true },
    { name: 'EUR/USD', count: 24, netFlow: -34, isPositive: false },
    { name: 'SOL/USDT', count: 19, netFlow: 45, isPositive: true },
    { name: 'XRP/USDT', count: 15, netFlow: -22, isPositive: false },
  ];

  const trendData = [120, 145, 98, 167, 134, 189, 156];
  const maxTrend = Math.max(...trendData);
  const minTrend = Math.min(...trendData);
  const trendRange = maxTrend - minTrend || 1;

  return (
    <div className="grid grid-cols-1 lg:grid-cols-[3fr_2fr] gap-4">
      {/* Left: Deep Analysis */}
      <motion.div
        initial={{ opacity: 0, y: 30 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.1, duration: 0.4, ease: [0.16, 1, 0.3, 1] as [number, number, number, number] }}
        className="rounded-lg border overflow-hidden"
        style={{ backgroundColor: 'var(--bg-secondary)', borderColor: 'var(--border-subtle)', borderLeft: '3px solid var(--accent-gold)' }}
      >
        <div className="flex items-center justify-between px-4 py-3 border-b" style={{ borderColor: 'var(--border-subtle)' }}>
          <div className="flex items-center gap-2">
            <Brain size={16} style={{ color: 'var(--accent-purple)' }} />
            <span className="text-sm font-semibold" style={{ color: 'var(--text-primary)' }}>Institutional Analysis</span>
          </div>
          <span
            className="text-[10px] px-2 py-0.5 rounded-full"
            style={{ backgroundColor: 'rgba(139,92,246,0.15)', color: 'var(--accent-purple)' }}
          >
            Generated by Claude
          </span>
        </div>
        <div className="p-4 space-y-4">
          <div>
            <h4 className="text-xs font-semibold mb-1" style={{ color: 'var(--accent-gold)' }}>Market Context</h4>
            <p className="text-sm leading-relaxed" style={{ color: 'var(--text-secondary)' }}>
              Institutional flows show a net positive bias across crypto markets, with Bitcoin and Ethereum dominating inflows.
              The concentration of large block trades suggests hedge fund rebalancing activity ahead of month-end.
            </p>
          </div>
          <div>
            <h4 className="text-xs font-semibold mb-1" style={{ color: 'var(--accent-gold)' }}>Flow Patterns</h4>
            <p className="text-sm leading-relaxed" style={{ color: 'var(--text-secondary)' }}>
              Accumulation patterns are visible in BTC with consistent buy pressure above $50M per hour.
              Distribution in altcoins suggests rotation into majors as market participants de-risk.
            </p>
          </div>
          <div>
            <h4 className="text-xs font-semibold mb-1" style={{ color: 'var(--accent-gold)' }}>Key Observations</h4>
            <ul className="text-sm space-y-1" style={{ color: 'var(--text-secondary)' }}>
              <li className="flex items-start gap-2">
                <span style={{ color: 'var(--accent-gold)' }}>•</span>
                <span>BTC seeing the largest inflows from Coinbase and Binance</span>
              </li>
              <li className="flex items-start gap-2">
                <span style={{ color: 'var(--accent-gold)' }}>•</span>
                <span>ETH accumulation by quant funds ahead of protocol upgrades</span>
              </li>
              <li className="flex items-start gap-2">
                <span style={{ color: 'var(--accent-gold)' }}>•</span>
                <span>FX flows indicate dollar weakness hedging via EUR/USD</span>
              </li>
            </ul>
          </div>
          <div>
            <h4 className="text-xs font-semibold mb-1" style={{ color: 'var(--accent-gold)' }}>Outlook</h4>
            <p className="text-sm leading-relaxed" style={{ color: 'var(--text-secondary)' }}>
              Expect continued institutional accumulation in BTC/ETH through the week.
              Forex flows suggest defensive positioning with slight risk-off bias.
            </p>
          </div>
          <div className="text-[10px] pt-2" style={{ color: 'var(--text-muted)', borderTop: '1px solid var(--border-subtle)' }}>
            Generated: {new Date().toLocaleTimeString('pl-PL', { hour: '2-digit', minute: '2-digit' })} UTC
          </div>
        </div>
      </motion.div>

      {/* Right: Flow Summary */}
      <div className="space-y-4">
        {/* Flow Breakdown (Donut) */}
        <motion.div
          initial={{ opacity: 0, y: 30 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.2, duration: 0.4, ease: [0.16, 1, 0.3, 1] as [number, number, number, number] }}
          className="rounded-lg border overflow-hidden"
          style={{ backgroundColor: 'var(--bg-secondary)', borderColor: 'var(--border-subtle)' }}
        >
          <div className="px-4 py-3 border-b" style={{ borderColor: 'var(--border-subtle)' }}>
            <span className="text-sm font-semibold" style={{ color: 'var(--text-primary)' }}>Flow Breakdown</span>
          </div>
          <div className="p-4">
            {/* Simple donut using conic gradient */}
            <div className="flex items-center gap-4">
              <div
                className="w-24 h-24 rounded-full shrink-0"
                style={{
                  background: `conic-gradient(
                    ${breakdown.map((b, i) => `${b.color} ${i === 0 ? 0 : breakdown.slice(0, i).reduce((s, x) => s + x.pct, 0)}% ${breakdown.slice(0, i + 1).reduce((s, x) => s + x.pct, 0)}%`).join(', ')}
                  )`,
                  position: 'relative',
                }}
              >
                <div
                  className="absolute inset-3 rounded-full flex items-center justify-center"
                  style={{ backgroundColor: 'var(--bg-secondary)' }}
                >
                  <span className="text-xs font-bold" style={{ fontFamily: "'JetBrains Mono', monospace", color: 'var(--text-primary)' }}>
                    +$284M
                  </span>
                </div>
              </div>
              <div className="flex-1 space-y-1.5">
                {breakdown.map((b) => (
                  <div key={b.category} className="flex items-center justify-between">
                    <div className="flex items-center gap-1.5">
                      <span className="w-2 h-2 rounded-full" style={{ backgroundColor: b.color }} />
                      <span className="text-[11px]" style={{ color: 'var(--text-secondary)' }}>{b.category}</span>
                    </div>
                    <span className="text-[11px] font-medium" style={{ fontFamily: "'JetBrains Mono', monospace", color: 'var(--text-primary)' }}>
                      {b.pct}%
                    </span>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </motion.div>

        {/* Top Movers */}
        <motion.div
          initial={{ opacity: 0, y: 30 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.3, duration: 0.4, ease: [0.16, 1, 0.3, 1] as [number, number, number, number] }}
          className="rounded-lg border overflow-hidden"
          style={{ backgroundColor: 'var(--bg-secondary)', borderColor: 'var(--border-subtle)' }}
        >
          <div className="px-4 py-3 border-b" style={{ borderColor: 'var(--border-subtle)' }}>
            <span className="text-sm font-semibold" style={{ color: 'var(--text-primary)' }}>Most Active Instruments</span>
          </div>
          <div className="p-4 space-y-3">
            {topMovers.map((m, i) => (
              <motion.div
                key={m.name}
                initial={{ opacity: 0, x: 15 }}
                animate={{ opacity: 1, x: 0 }}
                transition={{ delay: 0.4 + i * 0.08, duration: 0.3 }}
              >
                <div className="flex items-center justify-between mb-1">
                  <span className="text-xs font-medium" style={{ color: 'var(--text-primary)' }}>{m.name}</span>
                  <span className="text-[10px]" style={{ color: 'var(--text-muted)' }}>{m.count} tx</span>
                </div>
                <div className="w-full h-1.5 rounded-full overflow-hidden" style={{ backgroundColor: 'var(--bg-primary)' }}>
                  <motion.div
                    initial={{ width: 0 }}
                    animate={{ width: `${Math.min(100, Math.abs(m.netFlow))}%` }}
                    transition={{ delay: 0.5 + i * 0.08, duration: 0.5 }}
                    className="h-full rounded-full"
                    style={{ backgroundColor: m.isPositive ? 'var(--chart-bullish)' : 'var(--chart-bearish)' }}
                  />
                </div>
              </motion.div>
            ))}
          </div>
        </motion.div>

        {/* 7-Day Trend */}
        <motion.div
          initial={{ opacity: 0, y: 30 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.35, duration: 0.4, ease: [0.16, 1, 0.3, 1] as [number, number, number, number] }}
          className="rounded-lg border overflow-hidden"
          style={{ backgroundColor: 'var(--bg-secondary)', borderColor: 'var(--border-subtle)' }}
        >
          <div className="px-4 py-3 border-b" style={{ borderColor: 'var(--border-subtle)' }}>
            <span className="text-sm font-semibold" style={{ color: 'var(--text-primary)' }}>7-Day Trend</span>
          </div>
          <div className="p-4">
            {/* Mini SVG sparkline */}
            <svg viewBox={`0 0 ${trendData.length - 1} 50`} className="w-full h-12" preserveAspectRatio="none">
              <defs>
                <linearGradient id="trendGrad" x1="0" y1="0" x2="0" y2="1">
                  <stop offset="0%" stopColor="#00E396" stopOpacity="0.3" />
                  <stop offset="100%" stopColor="#00E396" stopOpacity="0" />
                </linearGradient>
              </defs>
              <path
                d={`M0,${50 - ((trendData[0] - minTrend) / trendRange) * 50} ${trendData.slice(1).map((v, i) => `L${i + 1},${50 - ((v - minTrend) / trendRange) * 50}`).join(' ')}`}
                fill="none"
                stroke="#00E396"
                strokeWidth="2"
              />
              <path
                d={`M0,${50 - ((trendData[0] - minTrend) / trendRange) * 50} ${trendData.slice(1).map((v, i) => `L${i + 1},${50 - ((v - minTrend) / trendRange) * 50}`).join(' ')} L${trendData.length - 1},50 L0,50 Z`}
                fill="url(#trendGrad)"
              />
            </svg>
            <div className="flex items-center gap-1.5 mt-2">
              <TrendingUp size={14} style={{ color: 'var(--chart-bullish)' }} />
              <span className="text-xs" style={{ color: 'var(--chart-bullish)' }}>
                Increasing institutional interest
              </span>
            </div>
          </div>
        </motion.div>
      </div>
    </div>
  );
}
